name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-25"


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjFkNmIyYzMtYTU3Ni00ZGZlLTk4NTktZDRmMGU4OTI5ODFmIiwidGVuYW50X2lkIjoiZDU5ZGNkYWQ0YWZhNzgwYzA1ZDYyZjFhYzllYTlmOThhMmUzODM0MTg5M2MyMWEzY2Q2NjhlNjY3NWM5MGViMiIsImludGVybmFsX3NlY3JldCI6IjcxZTc4NjhiLTcxMmItNGU4OC05YTNjLWQxZTM2Nzg1ZTFlZiJ9.vw5HEqwNf4T7CVn9u0MLg26O8NEjbU9oD8LLycye1g0"
JWT_SECRET = "a+zhEm8l76SYB5/x5ih7UtcZvXix/rKPCNqOPV14y9SUlEW7QdqR27HVaWY1aQXLid9ryImhfeeohutSypGtjw=="

